In [5]:
import pandas as pd

In [9]:
flights = pd.read_csv("../data/flightsData.csv",parse_dates=['CHSTOL'])
flights.head()

,CHOPER,CHFLTN,CHOPERD,CHSTOL,CHPTOL,CHAORD,CHLOC1,CHLOC1D,CHLOC1TH,CHLOC1T,CHLOC1CH,CHLOCCT,CHTERM,CHCINT,CHCKZN,CHRMINE,CHRMINH
0,LY,5132,EL AL ISRAEL AIRLINES,2025-06-18 10:15:00,2025-06-18T10:15:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,CANCELED,מבוטלת
1,LY,5442,EL AL ISRAEL AIRLINES,2025-06-18 08:00:00,2025-06-18T10:26:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,LANDED,נחתה
2,DIR,2032,FLYYO,2025-06-18 10:30:00,2025-06-18T10:30:00,A,HER,HERAKLION,הרקליון,HERAKLION,יוון,GREECE,3,NaN,NaN,CANCELED,מבוטלת
3,BZ,752,BLUE BIRD AIRWAYS,2025-06-18 10:40:00,2025-06-18T10:40:00,D,HER,HERAKLION,הרקליון,HERAKLION,יוון,GREECE,3,NaN,NaN,CANCELED,מבוטלת
4,6H,582,ISRAIR AIRLINES,2025-06-18 10:50:00,2025-06-18T10:50:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,CANCELED,מבוטלת

In [10]:
flights = flights.copy()

In [11]:
flights.columns = (
    flights.columns
        .str.strip()
        .str.lower()
        .str.replace(' ', '_')
        .str.replace('"', '')
)

In [13]:
column_rename_map = {
        "choper": "airline_code",
        "chfltn": "flight_number",
        "choperd": "airline_name",
        "chstol": "scheduled_takeoff",
        "chptol": "actual_takeoff",
        "chaord": "terminal_direction",
        "chloc1": "destination_airport_code",
        "chloc1d": "destination_airport_name_eng",
        "chloc1th": "destination_city_name_heb",
        "chloc1t": "destination_city_name_eng",
        "chloc1ch": "destination_country_name_heb",
        "chlocct": "destination_country_name_eng",
        "chterm": "terminal",
        "chcint": "international_indicator",
        "chckzn": "security_zone",
        "chrmine": "status_eng",
        "chrminh": "status_heb"
    }

flights.rename(columns=column_rename_map, inplace=True)
flights.head()

,airline_code,flight_number,airline_name,scheduled_takeoff,actual_takeoff,terminal_direction,destination_airport_code,destination_airport_name_eng,destination_city_name_heb,destination_city_name_eng,destination_country_name_heb,destination_country_name_eng,terminal,international_indicator,security_zone,status_eng,status_heb
0,LY,5132,EL AL ISRAEL AIRLINES,2025-06-18 10:15:00,2025-06-18T10:15:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,CANCELED,מבוטלת
1,LY,5442,EL AL ISRAEL AIRLINES,2025-06-18 08:00:00,2025-06-18T10:26:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,LANDED,נחתה
2,DIR,2032,FLYYO,2025-06-18 10:30:00,2025-06-18T10:30:00,A,HER,HERAKLION,הרקליון,HERAKLION,יוון,GREECE,3,NaN,NaN,CANCELED,מבוטלת
3,BZ,752,BLUE BIRD AIRWAYS,2025-06-18 10:40:00,2025-06-18T10:40:00,D,HER,HERAKLION,הרקליון,HERAKLION,יוון,GREECE,3,NaN,NaN,CANCELED,מבוטלת
4,6H,582,ISRAIR AIRLINES,2025-06-18 10:50:00,2025-06-18T10:50:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,CANCELED,מבוטלת

In [22]:
flights['date'] = flights['scheduled_takeoff'].dt.date
flights.head()

,airline_code,flight_number,airline_name,scheduled_takeoff,actual_takeoff,terminal_direction,destination_airport_code,destination_airport_name_eng,destination_city_name_heb,destination_city_name_eng,destination_country_name_heb,destination_country_name_eng,terminal,international_indicator,security_zone,status_eng,status_heb,date,canceled
0,LY,5132,EL AL ISRAEL AIRLINES,2025-06-18 10:15:00,2025-06-18T10:15:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,CANCELED,מבוטלת,2025-06-18,False
1,LY,5442,EL AL ISRAEL AIRLINES,2025-06-18 08:00:00,2025-06-18T10:26:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,LANDED,נחתה,2025-06-18,False
2,DIR,2032,FLYYO,2025-06-18 10:30:00,2025-06-18T10:30:00,A,HER,HERAKLION,הרקליון,HERAKLION,יוון,GREECE,3,NaN,NaN,CANCELED,מבוטלת,2025-06-18,False
3,BZ,752,BLUE BIRD AIRWAYS,2025-06-18 10:40:00,2025-06-18T10:40:00,D,HER,HERAKLION,הרקליון,HERAKLION,יוון,GREECE,3,NaN,NaN,CANCELED,מבוטלת,2025-06-18,False
4,6H,582,ISRAIR AIRLINES,2025-06-18 10:50:00,2025-06-18T10:50:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,CANCELED,מבוטלת,2025-06-18,False

In [28]:
flights['status_eng'] = flights['status_eng'].str.lower()

In [29]:
flights['canceled'] = flights['status_eng'] == 'canceled'

In [30]:
daily_cancel_rate = flights.groupby('date')['canceled'].mean().reset_index()

In [31]:
daily_cancel_rate.rename(columns={'canceled': 'cancel_rate'}, inplace=True)

In [32]:
daily_cancel_rate['cancel_rate'] *= 100

In [33]:
daily_cancel_rate

         date  cancel_rate
0  2025-06-18    84.158416
1  2025-06-19    85.576923
2  2025-06-20   100.000000
3  2025-06-21   100.000000
4  2025-06-22   100.000000