In [2]:
import pandas as pd

In [4]:
flights = pd.read_csv("../data/flightsData.csv")
flights.head()

,CHOPER,CHFLTN,CHOPERD,CHSTOL,CHPTOL,CHAORD,CHLOC1,CHLOC1D,CHLOC1TH,CHLOC1T,CHLOC1CH,CHLOCCT,CHTERM,CHCINT,CHCKZN,CHRMINE,CHRMINH
0,LY,5132,EL AL ISRAEL AIRLINES,2025-06-18T10:15:00,2025-06-18T10:15:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,CANCELED,מבוטלת
1,LY,5442,EL AL ISRAEL AIRLINES,2025-06-18T08:00:00,2025-06-18T10:26:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,LANDED,נחתה
2,DIR,2032,FLYYO,2025-06-18T10:30:00,2025-06-18T10:30:00,A,HER,HERAKLION,הרקליון,HERAKLION,יוון,GREECE,3,NaN,NaN,CANCELED,מבוטלת
3,BZ,752,BLUE BIRD AIRWAYS,2025-06-18T10:40:00,2025-06-18T10:40:00,D,HER,HERAKLION,הרקליון,HERAKLION,יוון,GREECE,3,NaN,NaN,CANCELED,מבוטלת
4,6H,582,ISRAIR AIRLINES,2025-06-18T10:50:00,2025-06-18T10:50:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,CANCELED,מבוטלת

In [5]:
flights.columns

Index(['CHOPER', 'CHFLTN', 'CHOPERD', 'CHSTOL', 'CHPTOL', 'CHAORD', 'CHLOC1',
       'CHLOC1D', 'CHLOC1TH', 'CHLOC1T', 'CHLOC1CH', 'CHLOCCT', 'CHTERM',
       'CHCINT', 'CHCKZN', 'CHRMINE', 'CHRMINH'],
      dtype='object')

In [8]:
flights['CHPTOL'] = pd.to_datetime(flights['CHPTOL'], errors='coerce')
flights['CHPTOL'].head()

0   2025-06-18 10:15:00
1   2025-06-18 10:26:00
2   2025-06-18 10:30:00
3   2025-06-18 10:40:00
4   2025-06-18 10:50:00
Name: CHPTOL, dtype: datetime64[ns]

In [9]:
flights['year'] = flights['CHPTOL'].dt.year

In [10]:
flights.set_index('year', inplace=True)
flights.head()

,CHOPER,CHFLTN,CHOPERD,CHSTOL,CHPTOL,CHAORD,CHLOC1,CHLOC1D,CHLOC1TH,CHLOC1T,CHLOC1CH,CHLOCCT,CHTERM,CHCINT,CHCKZN,CHRMINE,CHRMINH
year,,,,,,,,,,,,,,,,,
2025,LY,5132,EL AL ISRAEL AIRLINES,2025-06-18T10:15:00,2025-06-18 10:15:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,CANCELED,מבוטלת
2025,LY,5442,EL AL ISRAEL AIRLINES,2025-06-18T08:00:00,2025-06-18 10:26:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,LANDED,נחתה
2025,DIR,2032,FLYYO,2025-06-18T10:30:00,2025-06-18 10:30:00,A,HER,HERAKLION,הרקליון,HERAKLION,יוון,GREECE,3,NaN,NaN,CANCELED,מבוטלת
2025,BZ,752,BLUE BIRD AIRWAYS,2025-06-18T10:40:00,2025-06-18 10:40:00,D,HER,HERAKLION,הרקליון,HERAKLION,יוון,GREECE,3,NaN,NaN,CANCELED,מבוטלת
2025,6H,582,ISRAIR AIRLINES,2025-06-18T10:50:00,2025-06-18 10:50:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,CANCELED,מבוטלת